---

- name: Install packages with apt
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python-pip
    - python-dev
    - libcairo2-dev
    - python-cairo
    - fontconfig
    - uwsgi
    - uwsgi-plugin-python
    - sudo
    - libffi-dev

- name: "Install Twisted 16.0.0 on trusty (never versions req a newer python-openssl)"
  pip:
    name: "Twisted==16.0.0"
  when: ansible_distribution_release == "trusty"

- name: Debian Jessie and 1.0.2+ | cffi needs to be updated to a newer version
  pip:
    name: "cffi==1.10.0"
  environment:
    PYTHONPATH: "{{ graphite_install_path }}/lib:{{ graphite_install_path }}/webapp"
  when: >
    ansible_distribution_release == "jessie" and
    graphite_install_version | version_compare("1.0.2", ">=")

- name: Install init.d script for carbon-cache
  template:
    src: debian_carbon_service.j2
    dest: /etc/init.d/carbon-cache
  notify: restart carbon-cache
  when: ansible_distribution_release == "trusty"

- name: Install systemd unit carbon-cache.service
  template:
    src: carbon_service_systemd.j2
    dest: /etc/systemd/system/carbon-cache.service
  when: ansible_distribution_release != "trusty"
  register: ccunit

- name: Reload systemd if unit file has changed
  shell: systemctl daemon-reload
  when: ccunit|changed
  notify: restart carbon-cache

- name: Check the install scripts perms
  file:
    path: "/etc/init.d/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - carbon-cache
  when: ansible_distribution_release == "trusty"

- name: Install uwsgi graphite config
  template:
    src: uwsgi_graphite.ini.j2
    dest: /etc/uwsgi/apps-available/graphite.ini
  notify: restart uwsgi

- name: Enable uwsgi graphite config
  file:
    src: /etc/uwsgi/apps-available/graphite.ini
    dest: /etc/uwsgi/apps-enabled/graphite.ini
    state: link
  notify: restart uwsgi

- name: Make sure we have /run/uwsgi/graphite
  file:
    path: /run/uwsgi/graphite
    state: directory
    owner: "{{ graphite_user }}"
    group: "{{ graphite_user }}"
