
- name: "create /etc/nginx/sites-available/graphite"
  copy:
    content: |

      log_format graphite '$remote_addr - $remote_user [$time_local] '
            '"$request" $status $body_bytes_sent '
            '$request_length $request_time '
            '"$http_referer" "$http_user_agent"';

      charset utf-8;
      access_log /var/log/nginx/graphite.access.log;
      error_log /var/log/nginx/graphite.error.log;

      upstream backend {
          server 127.0.0.1:8083;
          keepalive 1024;
      }

      server {
          listen *:8080;
          # the virtual host name of this
          # server_name graphite.example.com;
          underscores_in_headers on;

          # FIXME: Might not work?
          # https://github.com/hopsoft/docker-graphite-statsd/blob/master/conf/etc/nginx/sites-enabled/graphite-statsd.conf
          root /opt/graphite/webapp/content;
          index index.html;

          location / {
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_pass http://backend;
              proxy_http_version 1.1;
              proxy_pass_request_headers on;
              proxy_set_header Connection "keep-alive";
              proxy_store off;
              gzip on;
              gzip_proxied any;
              gzip_types *;

              include uwsgi_params;
              uwsgi_pass 127.0.0.1:3031;

              # Block any HTTP requests other than GET, HEAD, and OPTIONS
              limit_except GET HEAD OPTIONS {
                  deny all;
              }
          }

          location /static {
            alias /opt/graphite/webapp/content;
            expires max;
          }

          location /stub_status {
              stub_status on;
              access_log off;
              allow 192.168.1.0/24;
              allow 127.0.0.1;
              deny all;
          }

          location /nginx_status {
            stub_status on;
            access_log   off;
            allow 127.0.0.1;
            deny all;
          }

      }


    dest: "/etc/nginx/sites-available/graphite"
    owner: "root"
    group: "root"
    mode: 0644
  notify: restart nginx

- name: 'Create symlink for /etc/nginx/sites-enabled/graphite'
  file:
    src: "/etc/nginx/sites-available/graphite"
    dest: "/etc/nginx/sites-enabled/graphite"
    state: link
  notify: restart nginx


- name: 'delete symlink for /etc/nginx/sites-enabled/default'
  file:
    dest: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: restart nginx

# In ansible playbooks, handlers (such as to restart a service) normally happen at the end of a run. If you need ansible to run a handler between two tasks, there is "flush_handlers".
- name: flush handlers
  meta: flush_handlers
